group=dev.folia
mcVersion=26.2-pre-5
# This is the current API version for use in (paper-)plugin.yml files
# During snapshot cycles this should be the anticipated version of the release target
apiVersion=26.2
channel=ALPHA

paperRef=b1805edc53b758f16bc99034114264ad6985cead

org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.vfs.watch=false
